ShelterRazor/Models/Owner.cs
namespace ShelterRazor.Models
{
    public class Owner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Address { get; set; }
        public ICollection<Pet>? Pets { get; set; }
    }
}

ShelterRazor/Pages/AddOwner.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShelterRazor.DTO;
using ShelterRazor.Interfaces;
using ShelterRazor.Models;
using ShelterRazor.Repository;

namespace ShelterRazor.Pages
{
    public class AddOwnerModel : PageModel
    {
        private readonly IOwner _ownerRepository;
        private readonly IMapper _mapper;
        public AddOwnerModel(IOwner ownerRepository, IMapper mapper)
        {
            _ownerRepository = ownerRepository;
            _mapper = mapper;
        }

        [BindProperty]
        public int PetId { get; set; }
        [BindProperty]
        public Owner Owner { get; set; }


        public void OnGet(int id)
        {
            PetId = id;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(Owner.Name == null || Owner.Name.Length < 2)
            {
                TempData["Error"] = "Name must be 2 or more letters";
                return RedirectToPage("AddOwner");
            }
            if (Owner.SurName == null || Owner.SurName.Length < 2)
            {
                TempData["Error"] = "Surname must be 2 or more letters";
                return RedirectToPage("AddOwner");
            }
            if (Owner.Address == null || Owner.Address.Length < 2)
            {
                TempData["Error"] = "Address must be 2 or more letters";
                return RedirectToPage("AddOwner");
            }

            Owner owner = await _ownerRepository.GetOwnerByNameAndSurname(Owner.Name, Owner.SurName);
            if (owner == null) {
                await _ownerRepository.AddOwner(Owner);

                Pet pet = await _ownerRepository.GetPet(PetId);
                pet.Owner = Owner;
            }
            else
            {
                Pet pet = await _ownerRepository.GetPet(PetId);
                pet.Owner = owner;
            }

            await _ownerRepository.SaveChanges();
            return RedirectToPage("/Index");
        }
    }
}

ShelterRazor/Pages/DeletePet.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShelterRazor.DTO;
using ShelterRazor.Interfaces;

namespace ShelterRazor.Pages
{
    public class DeletePetModel : PageModel
    {
        private readonly IPet _petRepository;
        private readonly IMapper _mapper;
        public DeletePetModel(IMapper mapper, IPet petRepository)
        {
            _mapper = mapper;
            _petRepository = petRepository;
        }

        [BindProperty]
        public PetDTO Pet { get; set; }


        public async Task<IActionResult> OnGetAsync(int id)
        {

            Pet = _mapper.Map<PetDTO>(await _petRepository.GetPetById(id));
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _petRepository.DeletePet(Pet.Id);
            await _petRepository.SaveChanges();

            TempData["Success"] = "Pet was deleted successfully";
            return RedirectToPage("/Index");
        }
    }
}

ShelterRazor/Pages/DetailedPet.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShelterRazor.DTO;
using ShelterRazor.Interfaces;
using ShelterRazor.Models;
using ShelterRazor.Models.Enums;
using ShelterRazor.Repository;

namespace ShelterRazor.Pages
{
    public class DetailedPetModel : PageModel
    {
        private readonly IPet _petRepository;
        private readonly IOwner _ownertRepository;
        private readonly IMapper _mapper;
        private readonly IPetShelter _shelterRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public DetailedPetModel(IPet petRepository, IMapper mapper, IPetShelter shelterRepository,
            IOwner ownerRepository, IWebHostEnvironment webHostEnvironment)
        {
            _petRepository = petRepository;
            _ownertRepository = ownerRepository;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
            _shelterRepository = shelterRepository;
        }

        [BindProperty]
        public IFormFile Photo { get; set; }
        [BindProperty]
        public PetDTO Pet {  get; set; }
        public SelectList Kinds { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Kinds = new SelectList(Enum.GetValues(typeof(KindsOfAnimal)).Cast<KindsOfAnimal>().ToList());

            if (id != 0) 
            { 
                Pet = _mapper.Map<PetDTO>(await _petRepository.GetPetById(id));
                if (Pet == null)
                {
                    return RedirectToPage("/Error");
                }
            }
            else
            {
                Pet = new PetDTO()
                {
                    Gender = 'M'
                };
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (Pet.Name == null) { 
                TempData["Error"] = "Pet name cannot be null";
                return RedirectToPage("/DetailedPet");
            } else if (Pet.Gender != 'M' && Pet.Gender != 'F')
            {
                TempData["Error"] = "Pet gender must be M or F";
                return RedirectToPage("/DetailedPet");
            } else if (Pet.PetShelterAddress == null)
            {
                TempData["Error"] = "Pet shelter address cannot be null";
                return RedirectToPage("/DetailedPet");
            } else if (Pet.Breed == null)
            {
                TempData["Error"] = "Pet breed cannot be null";
                return RedirectToPage("/DetailedPet");
            }
            if (Photo != null)
                Pet.ImgSrc = UploadImage();


            if (Pet.Id == 0)
            {
                Pet pet = _mapper.Map<Pet>(Pet);

                pet.PetShelter = await _shelterRepository.GetShelterByAddress(Pet.PetShelterAddress);
                if (pet.PetShelter == null)
                {
                    TempData["Error"] = "Pet shelter with this address dont't exist";
                    return RedirectToPage("/DetailedPet");
                }

                await _petRepository.AddPet(pet);
                await _petRepository.SaveChanges();
                TempData["Success"] = "Pet was successfully added";

                return RedirectToPage("/Index");
            }
            else
            {
                Pet pet = await _petRepository.GetPetById(Pet.Id);
                pet.PetShelter = await _shelterRepository.GetShelterByAddress(Pet.PetShelterAddress);

                if (pet.PetShelter == null)
                {
                    TempData["Error"] = "Pet shelter with this address dont't exist";
                    return RedirectToPage("/DetailedPet");
                }

                pet.Name = Pet.Name;
                pet.Age = Pet.Age;
                pet.Gender = Pet.Gender;
                pet.Breed = Pet.Breed;
                pet.KindOfAnimal = Pet.KindOfAnimal;
                pet.ImgSrc = Pet.ImgSrc;

                await _petRepository.UpdatePet(pet);
            }

            await _petRepository.SaveChanges();
            TempData["Success"] = "Pet was successfully updated";

            return RedirectToPage("/Index");

            
        }

        private string UploadImage()
        {
            string imgFolderSrc = Path.Combine(_webHostEnvironment.WebRootPath, "images");
            string uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
            string filePath = Path.Combine(imgFolderSrc, uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                Photo.CopyTo(fileStream);
            }
            return "/images/" + uniqueFileName;
        }
    }
}

ShelterRazor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ShelterRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

ShelterRazor/Pages/Index.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShelterRazor.DTO;
using ShelterRazor.Interfaces;
using ShelterRazor.Models;

namespace ShelterRazor.Pages
{
    public class PetsModel : PageModel
    {
        private readonly IPet _petRepository;
        private readonly IMapper _mapper;

        public PetsModel(IPet petRepository, IMapper mapper)
        {
            _petRepository = petRepository;
            _mapper = mapper;
        }


        [BindProperty]
        public string Filter { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Search {  get; set; }


        public ICollection<PetDTO> Pets { get; set; }

        public async Task OnGetAsync(string? filter = null)
        {
            switch (filter)
            {
                case "all":
                    Pets = await _petRepository.GetAllPets();
                    break;
                case "withoutowners":
                    Pets = _mapper.Map<ICollection<PetDTO>>(await _petRepository.GetPetsWithoutOwner());
                    break;
                default:
                    if (Search != null)
                    {
                        Pets = _mapper.Map<ICollection<PetDTO>>(await _petRepository.GetPetsWithBreed(Search));
                        break;
                    }
                    if (filter != null)
                    {
                        PetShelter petShelter = await _petRepository.GetShelter(filter);
                        Pets = _mapper.Map<ICollection<PetDTO>>(petShelter.Pets);
                        break;
                    }
                    Pets = await _petRepository.GetAllPets();
                    break;
            }
        }
    }
}

ShelterRazor/Pages/Owners.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShelterRazor.Interfaces;
using ShelterRazor.Models;

namespace ShelterRazor.Pages
{
    public class OwnersModel : PageModel
    {
        private readonly IOwner _ownerRepository;

        public OwnersModel(IOwner ownerRepos)
        {
            _ownerRepository = ownerRepos;
        }

        [BindProperty]
        public ICollection<Owner> Owners { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id = 0)
        {
            if (id != 0)
            {
                await _ownerRepository.DeleteOwner(id.Value);
                await _ownerRepository.SaveChanges();
                return RedirectToPage("/Owners");
            }

            Owners = await _ownerRepository.GetOwners();
            return Page();
        }
    }
}

ShelterRazor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ShelterRazor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

ShelterRazor/Pages/Shelters.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShelterRazor.Interfaces;
using ShelterRazor.Models;

namespace ShelterRazor.Pages
{
    public class SheltersModel : PageModel
    {
        private readonly IPetShelter _shelterRepository;

        public SheltersModel(IPetShelter shelterRepository)
        {
            _shelterRepository = shelterRepository;
        }

        [BindProperty]
        public ICollection<PetShelter> PetShelters { get; set; }

        public async Task OnGetAsync()
        {
            PetShelters = await _shelterRepository.PetShelters();
        }
    }
}

ShelterRazor/ViewComponents/KindsCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShelterRazor.Interfaces;
using ShelterRazor.Models;
using ShelterRazor.Models.Enums;

namespace ShelterRazor.ViewComponents
{
    public class KindsCountViewComponent : ViewComponent
    {
        private readonly IPet _petRepository;

        public KindsCountViewComponent(IPet petRepository)
        {
            _petRepository = petRepository;
        }

        public IViewComponentResult Invoke(KindsOfAnimal? kind = null)
        {
            ICollection<KindsCount> result = new List<KindsCount>();

            if (kind == null)
                result = _petRepository.GetPetKindsCount();
            else
                result.Add(_petRepository.GetPetKindsCount(kind.Value));

            return View(result);
        }
    }
}

ShelterRazor/Pages/AddOwner.cshtml
@page "{id}"
@model ShelterRazor.Pages.AddOwnerModel
@{
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="~/css/addowner.css" />
    </head>
    <body>
        <form method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="PetId" />

            <h1 class="title">Add owner</h1>
            <div class="shadow p-3 mb-5 bg-white rounded">
                <div class="d-flex justify-content-around">
                    <div>
                        <span>Name:</span><input class="card-title" asp-for="Owner.Name"/>
                    </div>
                    <div>
                         <span>Surname:</span><input class="card-title" asp-for="Owner.SurName" />

                    </div>
                    <div>
                         <span>Address:</span><input class="card-title" asp-for="Owner.Address" />
                    </div>
                </div>
                <div class="d-flex" style="margin-top:0.5%">
                    <button type="submit" class="btn btn-success">Save Changes</button>
                    <span style="margin-left:1%" class="text-danger" style="margin-top:0.5%;">@TempData["Error"]</span>
                </div>
            </div>
        </form>
    </body>
}

ShelterRazor/Pages/DeletePet.cshtml
@page "{id}"
@model ShelterRazor.Pages.DeletePetModel
@{
    <style>
        .margin {
            margin-top: 6%;
            text-align: center;
        }
        p{
            font-size: 18px;
        }
    </style>
    <div class="shadow p-3 mb-5 bg-white rounded margin">
        <h1 class="title">Delete @Model.Pet.Name</h1>
        <p>Pet Id: @Model.Pet.Id</p>
        <p>Pet Age: @Model.Pet.Age</p>
        <p>Pet Breed: @Model.Pet.Breed</p>

        @if(Model.Pet.OwnerAddress != null)
        {
            <p>Owner Name: @Model.Pet.OwnerName @Model.Pet.OwnerSurName</p>
            <p>Owner Address: @Model.Pet.OwnerAddress</p>
        }

        <p>Are you sure you want do delete this pet?</p>

        <form method="post">
            <button type="submit" class="btn btn-success">Yes</button>
            <a class="btn btn-danger" asp-page="/Index">No</a>
        </form>
    </div>
}

ShelterRazor/Pages/DetailedPet.cshtml
@page "{id}"
@model ShelterRazor.Pages.DetailedPetModel
@{
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="~/css/detailedpet.css" />
    </head>
    <body>
        <form method="post" enctype="multipart/form-data">
            <h1 class="title">Detailed Pet</h1>

            @await Component.InvokeAsync("KindsCount", new { kind = Model.Pet.KindOfAnimal })


            <div class="shadow p-3 mb-5 bg-white rounded">
                <div class="d-flex justify-content-around">
                    @if (Model.Pet.Name != null)
                    {
                        <img class="img-param" src="@Model.Pet.ImgSrc"/>
                    }

                    <div class="flex-coloumn">
                        <input type="hidden" asp-for="Pet.Id" />
                        <input type="hidden" asp-for="Pet.OwnerId" />
                        <input type="hidden" asp-for="Pet.PetShelterId" />
                        <input type="hidden" asp-for="Pet.ImgSrc" />

                        <span>Name:</span><input class="card-title" asp-for="Pet.Name" placeholder="@Model.Pet.Name" />
                        <span>Age:</span><input class="card-title" asp-for="Pet.Age" min="0" placeholder="@Model.Pet.Age" />
                        <span>Gender:</span><input class="card-title" asp-for="Pet.Gender" placeholder="@Model.Pet.Gender" />
                    </div>

                    <div class="flex-coloumn">
                        <span>Kind:</span><select asp-for="Pet.KindOfAnimal" asp-items="Model.Kinds" style="margin-left:5%; margin-bottom:4%;"></select>
                        <span>Breed:</span><input class="card-title" asp-for="Pet.Breed" placeholder="@Model.Pet.Breed"/>
                        <span>Pet shelter address:</span><input class="card-title" asp-for="Pet.PetShelterAddress" placeholder="@Model.Pet.PetShelterAddress" />
                    </div>

                    @if (Model.Pet.Name != null)
                    {
                        <div class="flex-coloumn">
                            @if (Model.Pet.OwnerName != null)
                            {
                                <div style="margin-top:10%;">
                                    <span>Date of taking:</span><br/>
                                    <span class="card-title">@Model.Pet.DateOfTaking</span>
                                </div>
                                <div style="margin-top:12%;">
                                    <span>Owner name:</span><br/>
                                    <span class="card-title">@Model.Pet.OwnerSurName</span>
                                </div>
                                <div style="margin-top:12%;">
                                    <span>Owner address:</span><br/>
                                    <span class="card-title">@Model.Pet.OwnerAddress</span>
                                </div>
                            }
                        </div>
                    }
                </div>
                <div style="margin-top: 1%;" class="d-flex justify-content-around">
                    <div style="margin-left:7%;">
                        <input asp-for="Photo" class="custom-file-input form-control"/>
                    </div>
                    <button style="margin-left: 28%;" type="submit" class="btn btn-success">Save Changes</button>
                    <span class="text-danger" style="margin-top:0.5%;">@TempData["Error"]</span>
                </div>
            </div>
        </form>
    </body>
}

ShelterRazor/Pages/Index.cshtml
@page "{filter?}"
@model ShelterRazor.Pages.PetsModel
@{
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="~/css/index.css" />
    </head>
    <body>
        <h1 class="title">All Pets</h1>
        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success text-center">
                @TempData["Success"]
            </div>
        }

        @await Component.InvokeAsync("KindsCount")

        <div class="d-flex justify-content-around">
            <a asp-page="/Index" asp-route-filter="all" class="btn btn-outline-dark">Get all pets</a>
            <form method="get">
                <div class="d-flex">
                    <input asp-for="Search" placeholder="Full pet breed" style="height:38px"/>
                    <button type="submit" class="btn btn-success" style="margin-left:5%">Search</button>
                </div>
            </form>
            <a asp-page="/Index" asp-route-filter="withoutowners" class="btn btn-outline-dark">Get all pets without owners</a>
        </div>
        <div class="d-flex flex-lg-wrap justify-content-around flex-wrap">
            @foreach (var item in Model.Pets)
            {
                var imagesPath = $"{item.ImgSrc}";

                <div class="card-group">
                    <div class="card">
                        <img class="card-img-top img-param" src="@imagesPath" alt="Pet image" />
                        <div class="card-body">
                            <h5 class="card-title">@item.Name</h5>
                            <span class="card-text">Age: @item.Age</span>
                            <span class="card-text">Gender: @item.Gender</span>
                            <span class="card-text">Kind: @item.KindOfAnimal</span>
                            <span class="card-text">Breed: @item.Breed</span><br />
                            <span class="card-text">Pet shelter address: @item.PetShelterAddress</span><br />
                            <div>
                                @if (item.OwnerName != null)
                                {
                                    <span class="card-text">Date of taking: @item.DateOfTaking</span><br/>
                                    <span class="card-text">Owner name: @item.OwnerName</span><br/>
                                    <span class="card-text">Owner address: @item.OwnerAddress</span><br />
                                }
                            </div>
                        </div>
                        <div class="d-flex justify-content-around">
                            @if (item.OwnerName == null)
                            {
                                <a asp-page="/AddOwner" asp-route-id="@item.Id" class="btn btn-success">Choose</a>
                            }
                            <a asp-page="/DetailedPet" asp-route-id="@item.Id" class="btn btn-primary">Edit</a>
                            <a asp-page="/DeletePet" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                </div>
             }
        </div>
    </body>
}

ShelterRazor/Pages/Owners.cshtml
@page "{id}" 
@model ShelterRazor.Pages.OwnersModel
@{
    <style>
        .tittle{
            margin-top: 70px;
            margin-bottom: 15px;
            text-align: center;
        }
        span{
            font-size: 18px;
        }
        .pets{
            margin-left:2%;
        }
        .test{
            align-items: center;
        }
    </style>
    <h1 class="tittle">Owners</h1>
    <div class="flex-lg-wrap flex-wrap d-flex" style="margin-left: -3%;">
        @foreach (var item in Model.Owners)
        {
            <div class="card-group" style="width:20%; margin-left:3%;">
                <div class="card">
                    <div class="card-body">
                        <div style="height: 83%;">
                            <span>@item.Name @item.SurName</span><br/>
                            <span>Address: @item.Address</span><br />
                            <span>Pets:</span>
                            <div class="pets">
                                @foreach(var item2 in item.Pets)
                                {
                                    <span>@item2.Name -</span>
                                    <span>@item2.Breed</span>
                                    <br />
                                }
                            </div>
                        </div>
                        <div class="d-flex justify-content-center">
                            <a asp-page="/Owners" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        <br />
        }
    </div>
}

ShelterRazor/Pages/Shelters.cshtml
@page "{id}"
@model ShelterRazor.Pages.SheltersModel
@{
    <style>
        img{
            width: 300px;
            height: 300px;
        }
    </style>
    <body>
        <h1 style="margin-top: 5%; margin-bottom: 2%; text-align: center">Shelters</h1>
        <div class="d-flex flex-lg-wrap justify-content-around flex-wrap">
            @foreach (var item in Model.PetShelters)
            {
                var imagesPath = $"{item.ImgSrc}";

                <div class="card-group">
                    <div class="card">
                        <img class="card-img-top img-param" src="@imagesPath" alt="Pet image">
                        <div class="card-body">
                            <h2 style="text-align: center" class="card-title a-center">@item.Address</h2>
                        </div>
                        <div class="d-flex justify-content-around" style="margin-bottom: 3%">
                            <a asp-page="/Index" asp-route-filter="@item.Address" class="btn btn-success">Pets in shelter</a>
                            <a asp-page="/DeletePet" asp-route-id="@item.Id" class="btn btn-primary">Products</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </body>
}